// <auto-generated />
using Hotel_Management_Bigbang_Assessment1_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_Management_Bigbang_Assessment1_.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230527164054_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Authentication.RegisterModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("RegisterModel");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Amenities", b =>
                {
                    b.Property<int>("Amenitiesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Amenitiesid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Amenitiesid");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNo")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("CustId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomNo");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<int>("Amenitiesid")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.HasIndex("Amenitiesid");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Booking", b =>
                {
                    b.HasOne("Hotel_Management_Bigbang_Assessment1_.Authentication.RegisterModel", "Register")
                        .WithMany("Bookings")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hotel_Management_Bigbang_Assessment1_.Models.Hotel", "Hotel")
                        .WithMany("Bookings")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Management_Bigbang_Assessment1_.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomNo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Register");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Hotel", b =>
                {
                    b.HasOne("Hotel_Management_Bigbang_Assessment1_.Models.Amenities", "Amenities")
                        .WithMany("Hotels")
                        .HasForeignKey("Amenitiesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenities");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Room", b =>
                {
                    b.HasOne("Hotel_Management_Bigbang_Assessment1_.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Authentication.RegisterModel", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Amenities", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Hotel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Hotel_Management_Bigbang_Assessment1_.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
